export enum Semantic {
  OK = "OK",
  REDIRECT = "REDIRECT",
  TIMEOUT = "TIMEOUT",
  REQUEST_ERROR = "REQUEST_ERROR",
  INCOMPLETE_RESPONSE = "INCOMPLETE_RESPONSE",
  NOT_FOUND = "NOT_FOUND",
  RESPONSE_ERROR = "RESPONSE_ERROR",
}
