import { IncomingHttpHeaders } from "http";

import { dropAttr } from "../../utility";

export function parseHeaders(headers: IncomingHttpHeaders) {
  const dropped = [
    "accept-patch",
    "accept-ranges",
    "access-control-allow-credentials",
    "access-control-allow-headers",
    "access-control-allow-methods",
    "access-control-allow-origin",
    "access-control-expose-headers",
    "access-control-max-age",
    "access-control-request-headers",
    "access-control-request-method",
    "age",
    "allow",
    "alt-svc",
    "authorization",
    "content-language",
    "content-length",
    "content-location",
    "content-range",
    "date",
    "expect",
    "forwarded",
    "from",
    "if-match",
    "if-modified-since",
    "if-none-match",
    "if-unmodified-since",
    "last-modified",
    "pragma",
    "proxy-authenticate",
    "proxy-authorization",
    "public-key-pins",
    "range",
    "referer",
    "retry-after",
    "sec-websocket-accept",
    "sec-websocket-extensions",
    "sec-websocket-key",
    "sec-websocket-protocol",
    "sec-websocket-version",
    "strict-transport-security",
    "tk",
    "trailer",
    "upgrade",
    "user-agent",
    "vary",
    "via",
    "warning",
    "www-authenticate",
    'set-cookie',
    'report-to',
    'nel',
    'cf-request-id',
    'cf-cache-status',
    'x-content-type-options'
  ];

  return dropAttr(dropped, headers);
}
